name: unit-tests
run-name: ${{ github.actor }} is testing implementation
on: [push]
jobs:
    set-up-machine:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v4
              with:
                python-version: '3.10.11'
                cache: 'pip' # caching pip dependencies
            - run: pip install -r requirements.txt
            - run: pwd
            - run: cd mc_shapley
            - run: pwd
            - run: pytest
